package com.securechat.network;

/**
 * Listener interface for receiving status updates related to user operations.
 *
 * <p>Implementations can handle informational or error messages
 * generated by client network or session activities.
 */
public interface UserStatusUpdateListener {

    /**
     * Called when there is a status update to report.
     *
     * @param updateMessage a descriptive message about the user status or operation outcome
     */
    void onUserStatusUpdate(String updateMessage);
}
